# Generated by Django 6.0.6 on 2026-06-30 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Dominio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('default_role', models.CharField(blank=True, choices=[('COORDINADOR', 'Coordinador'), ('SUPERVISOR', 'Supervisor'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], help_text='Rol asignado a los usuarios de este dominio (Ejecutor si se deja vacío).', max_length=20, verbose_name='Rol por defecto')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dominio permitido',
                'verbose_name_plural': 'Dominios permitidos',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('default_role', models.CharField(blank=True, choices=[('COORDINADOR', 'Coordinador'), ('SUPERVISOR', 'Supervisor'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], max_length=20, verbose_name='Rol por defecto')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correo permitido',
                'verbose_name_plural': 'Correos permitidos',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COORDINADOR', 'Coordinador'), ('SUPERVISOR', 'Supervisor'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], default='EJECUTOR', max_length=20, verbose_name='Rol')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COORDINADOR', 'Coordinador'), ('SUPERVISOR', 'Supervisor'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], max_length=20)),
                ('capability', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
                'ordering': ['role', 'capability'],
                'unique_together': {('role', 'capability')},
            },
        ),
    ]
