# Generated by Django 6.0.6 on 2026-07-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_supervisor_experto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloweddomain',
            name='default_role',
            field=models.CharField(blank=True, choices=[('COORDINADOR', 'Coordinador'), ('EXPERTO', 'Experto'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], help_text='Rol asignado a los usuarios de este dominio (Ejecutor si se deja vacío).', max_length=20, verbose_name='Rol por defecto'),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='default_role',
            field=models.CharField(blank=True, choices=[('COORDINADOR', 'Coordinador'), ('EXPERTO', 'Experto'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], max_length=20, verbose_name='Rol por defecto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('COORDINADOR', 'Coordinador'), ('EXPERTO', 'Experto'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], default='EJECUTOR', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('COORDINADOR', 'Coordinador'), ('EXPERTO', 'Experto'), ('EJECUTOR', 'Ejecutor'), ('SEGUIMIENTO', 'Seguimiento')], max_length=20),
        ),
    ]
