# Generated by Django 5.2.15 on 2026-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_board_by_ticket_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextcloudOAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activo')),
                ('base_url', models.CharField(blank=True, help_text='Ej. https://nube.dominio (sin /remote.php/...).', max_length=500, verbose_name='URL base de Nextcloud')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=500, verbose_name='Client secret')),
                ('authorize_url', models.CharField(blank=True, help_text='Vacío = {base_url}/index.php/apps/oauth2/authorize', max_length=500, verbose_name='URL de autorización (override)')),
                ('token_url', models.CharField(blank=True, help_text='Vacío = {base_url}/index.php/apps/oauth2/api/v1/token', max_length=500, verbose_name='URL de token (override)')),
                ('userinfo_url', models.CharField(blank=True, help_text='Vacío = {base_url}/ocs/v2.php/cloud/user (API OCS)', max_length=500, verbose_name='URL de userinfo (override)')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de login Nextcloud',
                'verbose_name_plural': 'Configuración de login Nextcloud',
            },
        ),
    ]
