# Generated by Django 6.0.6 on 2026-07-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_unarchive_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nextcloud_uid',
            field=models.CharField(blank=True, help_text='Se completa solo al loguearse vía Nextcloud OAuth2 — usado para detectar que la sesión embebida quedó de otro usuario de Nextcloud.', max_length=255, verbose_name='UID de Nextcloud'),
        ),
    ]
