# Generated by Django 6.0.6 on 2026-07-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_nextcloud_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Apagado: se usa la configuración de correo del servidor (.env).', verbose_name='Usar esta configuración SMTP')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Servidor SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Puerto')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=500, verbose_name='Contraseña')),
                ('from_email', models.CharField(blank=True, help_text='Ej. SkyDesk Tickets <noreply@dominio>. Vacío = el del servidor.', max_length=255, verbose_name='Remitente')),
                ('notify_assignment', models.BooleanField(default=True, verbose_name='Enviar correo al asignar un ticket')),
                ('notify_comment', models.BooleanField(default=False, help_text='Los participantes siempre reciben la notificación in-app (campanita).', verbose_name='Enviar correo por cada mensaje de seguimiento')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de correo',
                'verbose_name_plural': 'Configuración de correo',
            },
        ),
    ]
