# Generated by Django 6.0.6 on 2026-07-14 01:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_administrador_same_caps_as_coordinador'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light', models.ImageField(blank=True, help_text='PNG/JPG/WEBP, máx. 2 MB. Vacío = logo por defecto de SkyDesk.', upload_to=accounts.models._branding_light_path, validators=[accounts.models._validate_logo_size], verbose_name='Logo (tema claro)')),
                ('logo_dark', models.ImageField(blank=True, help_text='Vacío = logo por defecto de SkyDesk.', upload_to=accounts.models._branding_dark_path, validators=[accounts.models._validate_logo_size], verbose_name='Logo (tema oscuro)')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de logo',
                'verbose_name_plural': 'Configuración de logo',
            },
        ),
    ]
