# Generated by Django 6.0.6 on 2026-09-29 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_seed_default_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandingConfig',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='alloweddomain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_domains', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='alloweddomain',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='nextcloudoauthconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nextcloud_oauth', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('company', 'role', 'capability')},
        ),
        migrations.AddConstraint(
            model_name='alloweddomain',
            constraint=models.UniqueConstraint(fields=('company', 'domain'), name='accounts_alloweddomain_company_domain_uniq'),
        ),
        migrations.AddConstraint(
            model_name='allowedemail',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='accounts_allowedemail_company_email_uniq'),
        ),
    ]
