# Generated by Django 6.0.6 on 2026-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_blockedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brand_name',
            field=models.CharField(default='Kanban', help_text='Título de la pestaña, pantalla de login y firma de los correos.', max_length=60, verbose_name='Nombre de marca'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='from_email',
            field=models.CharField(blank=True, help_text='Ej. Kanban Tickets <noreply@dominio>. Vacío = el del servidor.', max_length=255, verbose_name='Remitente'),
        ),
    ]
