# Generated by Django 6.0.6 on 2026-07-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Hash'),
        ),
    ]
