# Generated by Django 6.0.6 on 2026-07-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextcloudConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Activo')),
                ('base_url', models.CharField(blank=True, help_text='Ej. https://nube.dominio/remote.php/dav/files/<usuario>', max_length=500, verbose_name='URL base (WebDAV)')),
                ('user', models.CharField(blank=True, max_length=255, verbose_name='Usuario')),
                ('token', models.CharField(blank=True, max_length=500, verbose_name='App-password')),
                ('root', models.CharField(blank=True, default='SkyDesk-Tickets', max_length=255, verbose_name='Carpeta raíz')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Nextcloud',
                'verbose_name_plural': 'Configuración de Nextcloud',
            },
        ),
    ]
