# Generated by Django 6.0.6 on 2026-07-04 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_nextcloudconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='version_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='version_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='attachments.attachment'),
        ),
    ]
