# Generated by Django 6.0.6 on 2026-09-29 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_company_constraints'),
        ('attachments', '0005_company_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextcloudconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nextcloud_config', to='accounts.company'),
        ),
    ]
