# Generated by Django 6.0.6 on 2026-06-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Propuestas'), ('TODO', 'Por hacer'), ('IN_PROGRESS', 'En progreso'), ('WAITING', 'Esperando'), ('DONE', 'Hecho')], default='BACKLOG', max_length=20, verbose_name='Estado'),
        ),
    ]
