# Generated by Django 6.0.6 on 2026-06-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(choices=[('info', 'Azul'), ('success', 'Verde'), ('warning', 'Ámbar'), ('error', 'Rojo'), ('accent', 'Acento'), ('neutral', 'Gris'), ('secondary', 'Secundario')], default='neutral', max_length=20, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vence'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.label', verbose_name='Etiquetas'),
        ),
    ]
