# Generated by Django 6.0.6 on 2026-07-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_project_ticket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Necesidad'), ('TODO', 'Por hacer'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Concluido'), ('WAITING', 'Suspendido/Cancelado')], default='BACKLOG', max_length=20, verbose_name='Estado'),
        ),
    ]
