# Generated by Django 6.0.6 on 2026-07-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_assignee_remove_ticket_waiting_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_subproducts',
            field=models.BooleanField(default=False, help_text='Si se marca, cada ejecutor tiene su subticket independiente (avanza por separado). Si no, la tarea es colaborativa: un estado compartido que mueve cualquiera.', verbose_name='Tiene subproductos'),
        ),
    ]
