# Generated by Django 6.0.6 on 2026-07-01 04:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_has_subproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_in_progress',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Tiempo en En progreso'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_todo',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Tiempo en Por hacer'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Distinto de WAITING por el ejecutor: solo el coordinador lo fija/quita, y mientras está seteado el ticket queda bloqueado (no se puede mover).', null=True, verbose_name='Suspendido por coordinador'),
        ),
    ]
