# Generated by Django 6.0.6 on 2026-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_assignment_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
