# Generated by Django 6.0.6 on 2026-07-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='split_at',
            field=models.DateTimeField(blank=True, help_text='Si se marca, el ticket es un contenedor: se descompuso en partes (-1, -2…) y ya no aparece como card en el tablero; solo se ven sus partes.', null=True, verbose_name='Dividido en partes'),
        ),
    ]
