# Generated by Django 6.0.6 on 2026-07-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_split_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tickets.assignment'),
        ),
    ]
