# Generated by Django 6.0.6 on 2026-07-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticketevent_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status_before_suspend',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
