# Generated by Django 6.0.6 on 2026-07-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_assignment_status_before_suspend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.label', verbose_name='Actividades'),
        ),
    ]
