# Generated by Django 6.0.6 on 2026-07-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_label_options_alter_ticket_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Actividad', 'verbose_name_plural': 'Tipos de Actividad'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.label', verbose_name='Tipos de Actividad'),
        ),
    ]
