# Generated by Django 6.0.6 on 2026-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_label_options_alter_ticket_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_divided_part',
            field=models.BooleanField(default=False, help_text='Marca los hijos creados por "Dividir" (clon idéntico del padre, que sigue activo), a diferencia de los creados por "Derivar" (tarea nueva a completar a mano).', verbose_name='Es una parte dividida'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Entrada'), ('TODO', 'Por hacer'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Concluido'), ('WAITING', 'Suspendido/Cancelado')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Entrada'), ('TODO', 'Por hacer'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Concluido'), ('WAITING', 'Suspendido/Cancelado')], default='BACKLOG', max_length=20, verbose_name='Estado'),
        ),
    ]
