# Generated by Django 6.0.6 on 2026-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_is_divided_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código'),
        ),
    ]
